// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: protos/agent/v1/agent.proto

package agent

import (
	model "github.com/GOAT-Robotics/gtstudio-proto/protos/v1/model"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Json struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Json) Reset() {
	*x = Json{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Json) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Json) ProtoMessage() {}

func (x *Json) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Json.ProtoReflect.Descriptor instead.
func (*Json) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Json) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetAgentConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentConfigurationRequest) Reset() {
	*x = GetAgentConfigurationRequest{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentConfigurationRequest) ProtoMessage() {}

func (x *GetAgentConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentConfigurationRequest.ProtoReflect.Descriptor instead.
func (*GetAgentConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

type GetAgentConfigurationResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Configuration *model.AgentConfiguration `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentConfigurationResponse) Reset() {
	*x = GetAgentConfigurationResponse{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentConfigurationResponse) ProtoMessage() {}

func (x *GetAgentConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentConfigurationResponse.ProtoReflect.Descriptor instead.
func (*GetAgentConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *GetAgentConfigurationResponse) GetConfiguration() *model.AgentConfiguration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

type SendCommandResponseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *model.CommandResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCommandResponseRequest) Reset() {
	*x = SendCommandResponseRequest{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandResponseRequest) ProtoMessage() {}

func (x *SendCommandResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandResponseRequest.ProtoReflect.Descriptor instead.
func (*SendCommandResponseRequest) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *SendCommandResponseRequest) GetResponse() *model.CommandResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type SendCommandResponseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCommandResponseResponse) Reset() {
	*x = SendCommandResponseResponse{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandResponseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandResponseResponse) ProtoMessage() {}

func (x *SendCommandResponseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandResponseResponse.ProtoReflect.Descriptor instead.
func (*SendCommandResponseResponse) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *SendCommandResponseResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *SendCommandResponseResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetCommandRequestStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandFilter []string               `protobuf:"bytes,1,rep,name=command_filter,json=commandFilter,proto3" json:"command_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandRequestStreamRequest) Reset() {
	*x = GetCommandRequestStreamRequest{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandRequestStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandRequestStreamRequest) ProtoMessage() {}

func (x *GetCommandRequestStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandRequestStreamRequest.ProtoReflect.Descriptor instead.
func (*GetCommandRequestStreamRequest) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *GetCommandRequestStreamRequest) GetCommandFilter() []string {
	if x != nil {
		return x.CommandFilter
	}
	return nil
}

type GetActionRequestStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandFilter []string               `protobuf:"bytes,1,rep,name=command_filter,json=commandFilter,proto3" json:"command_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActionRequestStreamRequest) Reset() {
	*x = GetActionRequestStreamRequest{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActionRequestStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActionRequestStreamRequest) ProtoMessage() {}

func (x *GetActionRequestStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActionRequestStreamRequest.ProtoReflect.Descriptor instead.
func (*GetActionRequestStreamRequest) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *GetActionRequestStreamRequest) GetCommandFilter() []string {
	if x != nil {
		return x.CommandFilter
	}
	return nil
}

type GetCommandRequestStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *model.CommandRequest  `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandRequestStreamResponse) Reset() {
	*x = GetCommandRequestStreamResponse{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandRequestStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandRequestStreamResponse) ProtoMessage() {}

func (x *GetCommandRequestStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandRequestStreamResponse.ProtoReflect.Descriptor instead.
func (*GetCommandRequestStreamResponse) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *GetCommandRequestStreamResponse) GetRequest() *model.CommandRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *GetCommandRequestStreamResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type PostDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostDataResponse) Reset() {
	*x = PostDataResponse{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostDataResponse) ProtoMessage() {}

func (x *PostDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostDataResponse.ProtoReflect.Descriptor instead.
func (*PostDataResponse) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *PostDataResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type PostMultiDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*model.Datapoint     `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostMultiDataRequest) Reset() {
	*x = PostMultiDataRequest{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMultiDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMultiDataRequest) ProtoMessage() {}

func (x *PostMultiDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMultiDataRequest.ProtoReflect.Descriptor instead.
func (*PostMultiDataRequest) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *PostMultiDataRequest) GetData() []*model.Datapoint {
	if x != nil {
		return x.Data
	}
	return nil
}

type PostMultiDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostMultiDataResponse) Reset() {
	*x = PostMultiDataResponse{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMultiDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMultiDataResponse) ProtoMessage() {}

func (x *PostMultiDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMultiDataResponse.ProtoReflect.Descriptor instead.
func (*PostMultiDataResponse) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *PostMultiDataResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type StreamDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeleopStatus  bool                   `protobuf:"varint,1,opt,name=teleop_status,json=teleopStatus,proto3" json:"teleop_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamDataRequest) Reset() {
	*x = StreamDataRequest{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDataRequest) ProtoMessage() {}

func (x *StreamDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDataRequest.ProtoReflect.Descriptor instead.
func (*StreamDataRequest) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *StreamDataRequest) GetTeleopStatus() bool {
	if x != nil {
		return x.TeleopStatus
	}
	return false
}

type StreamDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*model.Datapoint     `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamDataResponse) Reset() {
	*x = StreamDataResponse{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDataResponse) ProtoMessage() {}

func (x *StreamDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDataResponse.ProtoReflect.Descriptor instead.
func (*StreamDataResponse) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *StreamDataResponse) GetMessages() []*model.Datapoint {
	if x != nil {
		return x.Messages
	}
	return nil
}

type GetRosCommandConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRosCommandConfigRequest) Reset() {
	*x = GetRosCommandConfigRequest{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRosCommandConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRosCommandConfigRequest) ProtoMessage() {}

func (x *GetRosCommandConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRosCommandConfigRequest.ProtoReflect.Descriptor instead.
func (*GetRosCommandConfigRequest) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{16}
}

type GetRosCommandConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	MapsDirectory string                 `protobuf:"bytes,2,opt,name=maps_directory,json=mapsDirectory,proto3" json:"maps_directory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRosCommandConfigResponse) Reset() {
	*x = GetRosCommandConfigResponse{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRosCommandConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRosCommandConfigResponse) ProtoMessage() {}

func (x *GetRosCommandConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRosCommandConfigResponse.ProtoReflect.Descriptor instead.
func (*GetRosCommandConfigResponse) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *GetRosCommandConfigResponse) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *GetRosCommandConfigResponse) GetMapsDirectory() string {
	if x != nil {
		return x.MapsDirectory
	}
	return ""
}

type GetRosSubscriptionConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRosSubscriptionConfigRequest) Reset() {
	*x = GetRosSubscriptionConfigRequest{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRosSubscriptionConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRosSubscriptionConfigRequest) ProtoMessage() {}

func (x *GetRosSubscriptionConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRosSubscriptionConfigRequest.ProtoReflect.Descriptor instead.
func (*GetRosSubscriptionConfigRequest) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{18}
}

type GetRosSubscriptionConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *Json                  `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRosSubscriptionConfigResponse) Reset() {
	*x = GetRosSubscriptionConfigResponse{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRosSubscriptionConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRosSubscriptionConfigResponse) ProtoMessage() {}

func (x *GetRosSubscriptionConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRosSubscriptionConfigResponse.ProtoReflect.Descriptor instead.
func (*GetRosSubscriptionConfigResponse) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{19}
}

func (x *GetRosSubscriptionConfigResponse) GetConfig() *Json {
	if x != nil {
		return x.Config
	}
	return nil
}

type GetSubscriptionRequestStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionRequestStreamRequest) Reset() {
	*x = GetSubscriptionRequestStreamRequest{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionRequestStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionRequestStreamRequest) ProtoMessage() {}

func (x *GetSubscriptionRequestStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionRequestStreamRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionRequestStreamRequest) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{20}
}

type GetSubscriptionRequestStreamResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Id            string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic         *model.StreamConfiguration `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Action        string                     `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionRequestStreamResponse) Reset() {
	*x = GetSubscriptionRequestStreamResponse{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionRequestStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionRequestStreamResponse) ProtoMessage() {}

func (x *GetSubscriptionRequestStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionRequestStreamResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionRequestStreamResponse) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{21}
}

func (x *GetSubscriptionRequestStreamResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetSubscriptionRequestStreamResponse) GetTopic() *model.StreamConfiguration {
	if x != nil {
		return x.Topic
	}
	return nil
}

func (x *GetSubscriptionRequestStreamResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type SendSubscriptionResponseRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Response      *model.SubscriptionsResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSubscriptionResponseRequest) Reset() {
	*x = SendSubscriptionResponseRequest{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSubscriptionResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSubscriptionResponseRequest) ProtoMessage() {}

func (x *SendSubscriptionResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSubscriptionResponseRequest.ProtoReflect.Descriptor instead.
func (*SendSubscriptionResponseRequest) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{22}
}

func (x *SendSubscriptionResponseRequest) GetResponse() *model.SubscriptionsResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type SendSubscriptionResponseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSubscriptionResponseResponse) Reset() {
	*x = SendSubscriptionResponseResponse{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSubscriptionResponseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSubscriptionResponseResponse) ProtoMessage() {}

func (x *SendSubscriptionResponseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSubscriptionResponseResponse.ProtoReflect.Descriptor instead.
func (*SendSubscriptionResponseResponse) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{23}
}

func (x *SendSubscriptionResponseResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *SendSubscriptionResponseResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ReceiveRosMessagesRequest struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	Id               string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ControlDatapoint *model.ControlDatapoint `protobuf:"bytes,2,opt,name=control_datapoint,json=controlDatapoint,proto3" json:"control_datapoint,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReceiveRosMessagesRequest) Reset() {
	*x = ReceiveRosMessagesRequest{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveRosMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveRosMessagesRequest) ProtoMessage() {}

func (x *ReceiveRosMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveRosMessagesRequest.ProtoReflect.Descriptor instead.
func (*ReceiveRosMessagesRequest) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{24}
}

func (x *ReceiveRosMessagesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReceiveRosMessagesRequest) GetControlDatapoint() *model.ControlDatapoint {
	if x != nil {
		return x.ControlDatapoint
	}
	return nil
}

type ReceiveRosMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveRosMessagesResponse) Reset() {
	*x = ReceiveRosMessagesResponse{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveRosMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveRosMessagesResponse) ProtoMessage() {}

func (x *ReceiveRosMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveRosMessagesResponse.ProtoReflect.Descriptor instead.
func (*ReceiveRosMessagesResponse) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{25}
}

func (x *ReceiveRosMessagesResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ReceiveRosMessagesResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *ReceiveRosMessagesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SendActionResponseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *model.ActionResponse  `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendActionResponseRequest) Reset() {
	*x = SendActionResponseRequest{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendActionResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendActionResponseRequest) ProtoMessage() {}

func (x *SendActionResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendActionResponseRequest.ProtoReflect.Descriptor instead.
func (*SendActionResponseRequest) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{26}
}

func (x *SendActionResponseRequest) GetResponse() *model.ActionResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type GetActionRequestStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *model.ActionRequest   `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActionRequestStreamResponse) Reset() {
	*x = GetActionRequestStreamResponse{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActionRequestStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActionRequestStreamResponse) ProtoMessage() {}

func (x *GetActionRequestStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActionRequestStreamResponse.ProtoReflect.Descriptor instead.
func (*GetActionRequestStreamResponse) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{27}
}

func (x *GetActionRequestStreamResponse) GetRequest() *model.ActionRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *GetActionRequestStreamResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type SendActionResponseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendActionResponseResponse) Reset() {
	*x = SendActionResponseResponse{}
	mi := &file_protos_agent_v1_agent_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendActionResponseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendActionResponseResponse) ProtoMessage() {}

func (x *SendActionResponseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_v1_agent_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendActionResponseResponse.ProtoReflect.Descriptor instead.
func (*SendActionResponseResponse) Descriptor() ([]byte, []int) {
	return file_protos_agent_v1_agent_proto_rawDescGZIP(), []int{28}
}

func (x *SendActionResponseResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *SendActionResponseResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_protos_agent_v1_agent_proto protoreflect.FileDescriptor

const file_protos_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1bprotos/agent/v1/agent.proto\x12\bv1.agent\x1a\x1aprotos/model/v1/text.proto\x1a\x1cprotos/model/v1/config.proto\x1a\x1eprotos/model/v1/commands.proto\x1a\x1dprotos/model/v1/actions.proto\x1a\x1fprotos/model/v1/datapoint.proto\"\x1c\n" +
	"\x04Json\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x1e\n" +
	"\x1cGetAgentConfigurationRequest\"c\n" +
	"\x1dGetAgentConfigurationResponse\x12B\n" +
	"\rconfiguration\x18\x01 \x01(\v2\x1c.v1.model.AgentConfigurationR\rconfiguration\"\x0f\n" +
	"\rHealthRequest\"\x10\n" +
	"\x0eHealthResponse\"S\n" +
	"\x1aSendCommandResponseRequest\x125\n" +
	"\bresponse\x18\x01 \x01(\v2\x19.v1.model.CommandResponseR\bresponse\"5\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"\\\n" +
	"\x1bSendCommandResponseResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12%\n" +
	"\x05error\x18\x02 \x01(\v2\x0f.v1.agent.ErrorR\x05error\"G\n" +
	"\x1eGetCommandRequestStreamRequest\x12%\n" +
	"\x0ecommand_filter\x18\x01 \x03(\tR\rcommandFilter\"F\n" +
	"\x1dGetActionRequestStreamRequest\x12%\n" +
	"\x0ecommand_filter\x18\x01 \x03(\tR\rcommandFilter\"m\n" +
	"\x1fGetCommandRequestStreamResponse\x122\n" +
	"\arequest\x18\x01 \x01(\v2\x18.v1.model.CommandRequestR\arequest\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\"*\n" +
	"\x10PostDataResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"?\n" +
	"\x14PostMultiDataRequest\x12'\n" +
	"\x04data\x18\x01 \x03(\v2\x13.v1.model.DatapointR\x04data\"/\n" +
	"\x15PostMultiDataResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"8\n" +
	"\x11StreamDataRequest\x12#\n" +
	"\rteleop_status\x18\x01 \x01(\bR\fteleopStatus\"E\n" +
	"\x12StreamDataResponse\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.v1.model.DatapointR\bmessages\"\x1c\n" +
	"\x1aGetRosCommandConfigRequest\"\\\n" +
	"\x1bGetRosCommandConfigResponse\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\x12%\n" +
	"\x0emaps_directory\x18\x02 \x01(\tR\rmapsDirectory\"!\n" +
	"\x1fGetRosSubscriptionConfigRequest\"J\n" +
	" GetRosSubscriptionConfigResponse\x12&\n" +
	"\x06config\x18\x01 \x01(\v2\x0e.v1.agent.JsonR\x06config\"%\n" +
	"#GetSubscriptionRequestStreamRequest\"\x83\x01\n" +
	"$GetSubscriptionRequestStreamResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\x05topic\x18\x02 \x01(\v2\x1d.v1.model.StreamConfigurationR\x05topic\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"^\n" +
	"\x1fSendSubscriptionResponseRequest\x12;\n" +
	"\bresponse\x18\x01 \x01(\v2\x1f.v1.model.SubscriptionsResponseR\bresponse\"a\n" +
	" SendSubscriptionResponseResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12%\n" +
	"\x05error\x18\x02 \x01(\v2\x0f.v1.agent.ErrorR\x05error\"t\n" +
	"\x19ReceiveRosMessagesRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12G\n" +
	"\x11control_datapoint\x18\x02 \x01(\v2\x1a.v1.model.ControlDatapointR\x10controlDatapoint\"i\n" +
	"\x1aReceiveRosMessagesResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"Q\n" +
	"\x19SendActionResponseRequest\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.v1.model.ActionResponseR\bresponse\"k\n" +
	"\x1eGetActionRequestStreamResponse\x121\n" +
	"\arequest\x18\x01 \x01(\v2\x17.v1.model.ActionRequestR\arequest\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\"[\n" +
	"\x1aSendActionResponseResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12%\n" +
	"\x05error\x18\x02 \x01(\v2\x0f.v1.agent.ErrorR\x05error2\xf6\v\n" +
	"\x0eAgentRosBridge\x12j\n" +
	"\x15GetAgentConfiguration\x12&.v1.agent.GetAgentConfigurationRequest\x1a'.v1.agent.GetAgentConfigurationResponse\"\x00\x12s\n" +
	"\x18GetRosSubscriptionConfig\x12).v1.agent.GetRosSubscriptionConfigRequest\x1a*.v1.agent.GetRosSubscriptionConfigResponse\"\x00\x12d\n" +
	"\x13GetRosCommandConfig\x12$.v1.agent.GetRosCommandConfigRequest\x1a%.v1.agent.GetRosCommandConfigResponse\"\x00\x12=\n" +
	"\x06Health\x12\x17.v1.agent.HealthRequest\x1a\x18.v1.agent.HealthResponse\"\x00\x12r\n" +
	"\x17GetCommandRequestStream\x12(.v1.agent.GetCommandRequestStreamRequest\x1a).v1.agent.GetCommandRequestStreamResponse\"\x000\x01\x12d\n" +
	"\x13SendCommandResponse\x12$.v1.agent.SendCommandResponseRequest\x1a%.v1.agent.SendCommandResponseResponse\"\x00\x12\x81\x01\n" +
	"\x1cGetSubscriptionRequestStream\x12-.v1.agent.GetSubscriptionRequestStreamRequest\x1a..v1.agent.GetSubscriptionRequestStreamResponse\"\x000\x01\x12s\n" +
	"\x18SendSubscriptionResponse\x12).v1.agent.SendSubscriptionResponseRequest\x1a*.v1.agent.SendSubscriptionResponseResponse\"\x00\x12n\n" +
	"\x19SendCommandResponseStream\x12$.v1.agent.SendCommandResponseRequest\x1a%.v1.agent.SendCommandResponseResponse\"\x00(\x010\x01\x12=\n" +
	"\bPostData\x12\x13.v1.model.Datapoint\x1a\x1a.v1.agent.PostDataResponse\"\x00\x12R\n" +
	"\rPostMultiData\x12\x1e.v1.agent.PostMultiDataRequest\x1a\x1f.v1.agent.PostMultiDataResponse\"\x00\x12M\n" +
	"\n" +
	"StreamData\x12\x1c.v1.agent.StreamDataResponse\x1a\x1b.v1.agent.StreamDataRequest\"\x00(\x010\x01\x12e\n" +
	"\x12ReceiveRosMessages\x12$.v1.agent.ReceiveRosMessagesResponse\x1a#.v1.agent.ReceiveRosMessagesRequest\"\x00(\x010\x01\x12o\n" +
	"\x16GetActionRequestStream\x12'.v1.agent.GetActionRequestStreamRequest\x1a(.v1.agent.GetActionRequestStreamResponse\"\x000\x01\x12a\n" +
	"\x12SendActionResponse\x12#.v1.agent.SendActionResponseRequest\x1a$.v1.agent.SendActionResponseResponse\"\x00B9Z7github.com/GOAT-Robotics/gtstudio-proto/protos/v1/agentb\x06proto3"

var (
	file_protos_agent_v1_agent_proto_rawDescOnce sync.Once
	file_protos_agent_v1_agent_proto_rawDescData []byte
)

func file_protos_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_protos_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_protos_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_agent_v1_agent_proto_rawDesc), len(file_protos_agent_v1_agent_proto_rawDesc)))
	})
	return file_protos_agent_v1_agent_proto_rawDescData
}

var file_protos_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_protos_agent_v1_agent_proto_goTypes = []any{
	(*Json)(nil),                                 // 0: v1.agent.Json
	(*GetAgentConfigurationRequest)(nil),         // 1: v1.agent.GetAgentConfigurationRequest
	(*GetAgentConfigurationResponse)(nil),        // 2: v1.agent.GetAgentConfigurationResponse
	(*HealthRequest)(nil),                        // 3: v1.agent.HealthRequest
	(*HealthResponse)(nil),                       // 4: v1.agent.HealthResponse
	(*SendCommandResponseRequest)(nil),           // 5: v1.agent.SendCommandResponseRequest
	(*Error)(nil),                                // 6: v1.agent.Error
	(*SendCommandResponseResponse)(nil),          // 7: v1.agent.SendCommandResponseResponse
	(*GetCommandRequestStreamRequest)(nil),       // 8: v1.agent.GetCommandRequestStreamRequest
	(*GetActionRequestStreamRequest)(nil),        // 9: v1.agent.GetActionRequestStreamRequest
	(*GetCommandRequestStreamResponse)(nil),      // 10: v1.agent.GetCommandRequestStreamResponse
	(*PostDataResponse)(nil),                     // 11: v1.agent.PostDataResponse
	(*PostMultiDataRequest)(nil),                 // 12: v1.agent.PostMultiDataRequest
	(*PostMultiDataResponse)(nil),                // 13: v1.agent.PostMultiDataResponse
	(*StreamDataRequest)(nil),                    // 14: v1.agent.StreamDataRequest
	(*StreamDataResponse)(nil),                   // 15: v1.agent.StreamDataResponse
	(*GetRosCommandConfigRequest)(nil),           // 16: v1.agent.GetRosCommandConfigRequest
	(*GetRosCommandConfigResponse)(nil),          // 17: v1.agent.GetRosCommandConfigResponse
	(*GetRosSubscriptionConfigRequest)(nil),      // 18: v1.agent.GetRosSubscriptionConfigRequest
	(*GetRosSubscriptionConfigResponse)(nil),     // 19: v1.agent.GetRosSubscriptionConfigResponse
	(*GetSubscriptionRequestStreamRequest)(nil),  // 20: v1.agent.GetSubscriptionRequestStreamRequest
	(*GetSubscriptionRequestStreamResponse)(nil), // 21: v1.agent.GetSubscriptionRequestStreamResponse
	(*SendSubscriptionResponseRequest)(nil),      // 22: v1.agent.SendSubscriptionResponseRequest
	(*SendSubscriptionResponseResponse)(nil),     // 23: v1.agent.SendSubscriptionResponseResponse
	(*ReceiveRosMessagesRequest)(nil),            // 24: v1.agent.ReceiveRosMessagesRequest
	(*ReceiveRosMessagesResponse)(nil),           // 25: v1.agent.ReceiveRosMessagesResponse
	(*SendActionResponseRequest)(nil),            // 26: v1.agent.SendActionResponseRequest
	(*GetActionRequestStreamResponse)(nil),       // 27: v1.agent.GetActionRequestStreamResponse
	(*SendActionResponseResponse)(nil),           // 28: v1.agent.SendActionResponseResponse
	(*model.AgentConfiguration)(nil),             // 29: v1.model.AgentConfiguration
	(*model.CommandResponse)(nil),                // 30: v1.model.CommandResponse
	(*model.CommandRequest)(nil),                 // 31: v1.model.CommandRequest
	(*model.Datapoint)(nil),                      // 32: v1.model.Datapoint
	(*model.StreamConfiguration)(nil),            // 33: v1.model.StreamConfiguration
	(*model.SubscriptionsResponse)(nil),          // 34: v1.model.SubscriptionsResponse
	(*model.ControlDatapoint)(nil),               // 35: v1.model.ControlDatapoint
	(*model.ActionResponse)(nil),                 // 36: v1.model.ActionResponse
	(*model.ActionRequest)(nil),                  // 37: v1.model.ActionRequest
}
var file_protos_agent_v1_agent_proto_depIdxs = []int32{
	29, // 0: v1.agent.GetAgentConfigurationResponse.configuration:type_name -> v1.model.AgentConfiguration
	30, // 1: v1.agent.SendCommandResponseRequest.response:type_name -> v1.model.CommandResponse
	6,  // 2: v1.agent.SendCommandResponseResponse.error:type_name -> v1.agent.Error
	31, // 3: v1.agent.GetCommandRequestStreamResponse.request:type_name -> v1.model.CommandRequest
	32, // 4: v1.agent.PostMultiDataRequest.data:type_name -> v1.model.Datapoint
	32, // 5: v1.agent.StreamDataResponse.messages:type_name -> v1.model.Datapoint
	0,  // 6: v1.agent.GetRosSubscriptionConfigResponse.config:type_name -> v1.agent.Json
	33, // 7: v1.agent.GetSubscriptionRequestStreamResponse.topic:type_name -> v1.model.StreamConfiguration
	34, // 8: v1.agent.SendSubscriptionResponseRequest.response:type_name -> v1.model.SubscriptionsResponse
	6,  // 9: v1.agent.SendSubscriptionResponseResponse.error:type_name -> v1.agent.Error
	35, // 10: v1.agent.ReceiveRosMessagesRequest.control_datapoint:type_name -> v1.model.ControlDatapoint
	36, // 11: v1.agent.SendActionResponseRequest.response:type_name -> v1.model.ActionResponse
	37, // 12: v1.agent.GetActionRequestStreamResponse.request:type_name -> v1.model.ActionRequest
	6,  // 13: v1.agent.SendActionResponseResponse.error:type_name -> v1.agent.Error
	1,  // 14: v1.agent.AgentRosBridge.GetAgentConfiguration:input_type -> v1.agent.GetAgentConfigurationRequest
	18, // 15: v1.agent.AgentRosBridge.GetRosSubscriptionConfig:input_type -> v1.agent.GetRosSubscriptionConfigRequest
	16, // 16: v1.agent.AgentRosBridge.GetRosCommandConfig:input_type -> v1.agent.GetRosCommandConfigRequest
	3,  // 17: v1.agent.AgentRosBridge.Health:input_type -> v1.agent.HealthRequest
	8,  // 18: v1.agent.AgentRosBridge.GetCommandRequestStream:input_type -> v1.agent.GetCommandRequestStreamRequest
	5,  // 19: v1.agent.AgentRosBridge.SendCommandResponse:input_type -> v1.agent.SendCommandResponseRequest
	20, // 20: v1.agent.AgentRosBridge.GetSubscriptionRequestStream:input_type -> v1.agent.GetSubscriptionRequestStreamRequest
	22, // 21: v1.agent.AgentRosBridge.SendSubscriptionResponse:input_type -> v1.agent.SendSubscriptionResponseRequest
	5,  // 22: v1.agent.AgentRosBridge.SendCommandResponseStream:input_type -> v1.agent.SendCommandResponseRequest
	32, // 23: v1.agent.AgentRosBridge.PostData:input_type -> v1.model.Datapoint
	12, // 24: v1.agent.AgentRosBridge.PostMultiData:input_type -> v1.agent.PostMultiDataRequest
	15, // 25: v1.agent.AgentRosBridge.StreamData:input_type -> v1.agent.StreamDataResponse
	25, // 26: v1.agent.AgentRosBridge.ReceiveRosMessages:input_type -> v1.agent.ReceiveRosMessagesResponse
	9,  // 27: v1.agent.AgentRosBridge.GetActionRequestStream:input_type -> v1.agent.GetActionRequestStreamRequest
	26, // 28: v1.agent.AgentRosBridge.SendActionResponse:input_type -> v1.agent.SendActionResponseRequest
	2,  // 29: v1.agent.AgentRosBridge.GetAgentConfiguration:output_type -> v1.agent.GetAgentConfigurationResponse
	19, // 30: v1.agent.AgentRosBridge.GetRosSubscriptionConfig:output_type -> v1.agent.GetRosSubscriptionConfigResponse
	17, // 31: v1.agent.AgentRosBridge.GetRosCommandConfig:output_type -> v1.agent.GetRosCommandConfigResponse
	4,  // 32: v1.agent.AgentRosBridge.Health:output_type -> v1.agent.HealthResponse
	10, // 33: v1.agent.AgentRosBridge.GetCommandRequestStream:output_type -> v1.agent.GetCommandRequestStreamResponse
	7,  // 34: v1.agent.AgentRosBridge.SendCommandResponse:output_type -> v1.agent.SendCommandResponseResponse
	21, // 35: v1.agent.AgentRosBridge.GetSubscriptionRequestStream:output_type -> v1.agent.GetSubscriptionRequestStreamResponse
	23, // 36: v1.agent.AgentRosBridge.SendSubscriptionResponse:output_type -> v1.agent.SendSubscriptionResponseResponse
	7,  // 37: v1.agent.AgentRosBridge.SendCommandResponseStream:output_type -> v1.agent.SendCommandResponseResponse
	11, // 38: v1.agent.AgentRosBridge.PostData:output_type -> v1.agent.PostDataResponse
	13, // 39: v1.agent.AgentRosBridge.PostMultiData:output_type -> v1.agent.PostMultiDataResponse
	14, // 40: v1.agent.AgentRosBridge.StreamData:output_type -> v1.agent.StreamDataRequest
	24, // 41: v1.agent.AgentRosBridge.ReceiveRosMessages:output_type -> v1.agent.ReceiveRosMessagesRequest
	27, // 42: v1.agent.AgentRosBridge.GetActionRequestStream:output_type -> v1.agent.GetActionRequestStreamResponse
	28, // 43: v1.agent.AgentRosBridge.SendActionResponse:output_type -> v1.agent.SendActionResponseResponse
	29, // [29:44] is the sub-list for method output_type
	14, // [14:29] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_protos_agent_v1_agent_proto_init() }
func file_protos_agent_v1_agent_proto_init() {
	if File_protos_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_agent_v1_agent_proto_rawDesc), len(file_protos_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_protos_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_protos_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_protos_agent_v1_agent_proto = out.File
	file_protos_agent_v1_agent_proto_goTypes = nil
	file_protos_agent_v1_agent_proto_depIdxs = nil
}
