// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v6.31.1
// source: protos/model/v1/telemetry.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Robot Telemetry shared model
type RobotTelemetry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotPose    *Pose   `protobuf:"bytes,1,opt,name=robot_pose,json=robotPose,proto3" json:"robot_pose,omitempty"`          // Pose of the robot (position and orientation)
	Percentage   float64 `protobuf:"fixed64,2,opt,name=percentage,proto3" json:"percentage,omitempty"`                       // Battery percentage of the robot
	CurrentMap   string  `protobuf:"bytes,3,opt,name=current_map,json=currentMap,proto3" json:"current_map,omitempty"`       // The current map where the robot is operating
	CurrentState string  `protobuf:"bytes,4,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"` // Current state of the robot (e.g., "READY", "NAVIGATING", etc.)
}

func (x *RobotTelemetry) Reset() {
	*x = RobotTelemetry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_model_v1_telemetry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RobotTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotTelemetry) ProtoMessage() {}

func (x *RobotTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_v1_telemetry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotTelemetry.ProtoReflect.Descriptor instead.
func (*RobotTelemetry) Descriptor() ([]byte, []int) {
	return file_protos_model_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *RobotTelemetry) GetRobotPose() *Pose {
	if x != nil {
		return x.RobotPose
	}
	return nil
}

func (x *RobotTelemetry) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *RobotTelemetry) GetCurrentMap() string {
	if x != nil {
		return x.CurrentMap
	}
	return ""
}

func (x *RobotTelemetry) GetCurrentState() string {
	if x != nil {
		return x.CurrentState
	}
	return ""
}

type Pose struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position    *Position    `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`       // Position of the robot
	Orientation *Orientation `protobuf:"bytes,2,opt,name=orientation,proto3" json:"orientation,omitempty"` // Orientation of the robot
}

func (x *Pose) Reset() {
	*x = Pose{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_model_v1_telemetry_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pose) ProtoMessage() {}

func (x *Pose) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_v1_telemetry_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pose.ProtoReflect.Descriptor instead.
func (*Pose) Descriptor() ([]byte, []int) {
	return file_protos_model_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *Pose) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Pose) GetOrientation() *Orientation {
	if x != nil {
		return x.Orientation
	}
	return nil
}

type Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"` // X coordinate of the robot
	Y float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"` // Y coordinate of the robot
	Z float64 `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"` // Z coordinate (altitude) of the robot
}

func (x *Position) Reset() {
	*x = Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_model_v1_telemetry_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_v1_telemetry_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_protos_model_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *Position) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Position) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Orientation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	W float64 `protobuf:"fixed64,1,opt,name=w,proto3" json:"w,omitempty"` // W component of the quaternion
	X float64 `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"` // X component of the quaternion
	Y float64 `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"` // Y component of the quaternion
	Z float64 `protobuf:"fixed64,4,opt,name=z,proto3" json:"z,omitempty"` // Z component of the quaternion
}

func (x *Orientation) Reset() {
	*x = Orientation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_model_v1_telemetry_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Orientation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Orientation) ProtoMessage() {}

func (x *Orientation) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_v1_telemetry_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Orientation.ProtoReflect.Descriptor instead.
func (*Orientation) Descriptor() ([]byte, []int) {
	return file_protos_model_v1_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *Orientation) GetW() float64 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *Orientation) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Orientation) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Orientation) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

var File_protos_model_v1_telemetry_proto protoreflect.FileDescriptor

var file_protos_model_v1_telemetry_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x76,
	0x31, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0xa5, 0x01, 0x0a, 0x0e,
	0x52, 0x6f, 0x62, 0x6f, 0x74, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x12, 0x2d,
	0x0a, 0x0a, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x70, 0x6f, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x6f,
	0x73, 0x65, 0x52, 0x09, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x50, 0x6f, 0x73, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0a, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x61, 0x70, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x70, 0x12, 0x23,
	0x0a, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x22, 0x6f, 0x0a, 0x04, 0x50, 0x6f, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x37, 0x0a, 0x0b, 0x6f,
	0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4f, 0x72, 0x69, 0x65,
	0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x6f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x34, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c,
	0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01,
	0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x7a, 0x22, 0x45, 0x0a, 0x0b, 0x4f, 0x72,
	0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x77, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x77, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01,
	0x7a, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x47, 0x4f, 0x41, 0x54, 0x2d, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x2f, 0x67, 0x74,
	0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_model_v1_telemetry_proto_rawDescOnce sync.Once
	file_protos_model_v1_telemetry_proto_rawDescData = file_protos_model_v1_telemetry_proto_rawDesc
)

func file_protos_model_v1_telemetry_proto_rawDescGZIP() []byte {
	file_protos_model_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_protos_model_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_model_v1_telemetry_proto_rawDescData)
	})
	return file_protos_model_v1_telemetry_proto_rawDescData
}

var file_protos_model_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_model_v1_telemetry_proto_goTypes = []any{
	(*RobotTelemetry)(nil), // 0: v1.model.RobotTelemetry
	(*Pose)(nil),           // 1: v1.model.Pose
	(*Position)(nil),       // 2: v1.model.Position
	(*Orientation)(nil),    // 3: v1.model.Orientation
}
var file_protos_model_v1_telemetry_proto_depIdxs = []int32{
	1, // 0: v1.model.RobotTelemetry.robot_pose:type_name -> v1.model.Pose
	2, // 1: v1.model.Pose.position:type_name -> v1.model.Position
	3, // 2: v1.model.Pose.orientation:type_name -> v1.model.Orientation
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_model_v1_telemetry_proto_init() }
func file_protos_model_v1_telemetry_proto_init() {
	if File_protos_model_v1_telemetry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_model_v1_telemetry_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RobotTelemetry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_model_v1_telemetry_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Pose); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_model_v1_telemetry_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_model_v1_telemetry_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Orientation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_model_v1_telemetry_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_model_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_protos_model_v1_telemetry_proto_depIdxs,
		MessageInfos:      file_protos_model_v1_telemetry_proto_msgTypes,
	}.Build()
	File_protos_model_v1_telemetry_proto = out.File
	file_protos_model_v1_telemetry_proto_rawDesc = nil
	file_protos_model_v1_telemetry_proto_goTypes = nil
	file_protos_model_v1_telemetry_proto_depIdxs = nil
}
