// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.12.4
// source: protos/fleet_manager/v1/fleet_manager.proto

package fleet_manager

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	FleetManager_HerdCommandStream_FullMethodName    = "/v1.fleet_manager.FleetManager/HerdCommandStream"
	FleetManager_HerdServices_FullMethodName         = "/v1.fleet_manager.FleetManager/HerdServices"
	FleetManager_HerdRobotTelemetry_FullMethodName   = "/v1.fleet_manager.FleetManager/HerdRobotTelemetry"
	FleetManager_HerdTelemetry_FullMethodName        = "/v1.fleet_manager.FleetManager/HerdTelemetry"
	FleetManager_HerdHealthCheck_FullMethodName      = "/v1.fleet_manager.FleetManager/HerdHealthCheck"
	FleetManager_DockerStatsTelemetry_FullMethodName = "/v1.fleet_manager.FleetManager/DockerStatsTelemetry"
)

// FleetManagerClient is the client API for FleetManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FleetManagerClient interface {
	HerdCommandStream(ctx context.Context, opts ...grpc.CallOption) (FleetManager_HerdCommandStreamClient, error)
	HerdServices(ctx context.Context, in *HerdServiceRequest, opts ...grpc.CallOption) (*HerdServiceResponse, error)
	HerdRobotTelemetry(ctx context.Context, in *RobotTelemetryData, opts ...grpc.CallOption) (FleetManager_HerdRobotTelemetryClient, error)
	HerdTelemetry(ctx context.Context, opts ...grpc.CallOption) (FleetManager_HerdTelemetryClient, error)
	HerdHealthCheck(ctx context.Context, opts ...grpc.CallOption) (FleetManager_HerdHealthCheckClient, error)
	DockerStatsTelemetry(ctx context.Context, in *DockerTelemetryRequest, opts ...grpc.CallOption) (FleetManager_DockerStatsTelemetryClient, error)
}

type fleetManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetManagerClient(cc grpc.ClientConnInterface) FleetManagerClient {
	return &fleetManagerClient{cc}
}

func (c *fleetManagerClient) HerdCommandStream(ctx context.Context, opts ...grpc.CallOption) (FleetManager_HerdCommandStreamClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetManager_ServiceDesc.Streams[0], FleetManager_HerdCommandStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &fleetManagerHerdCommandStreamClient{ClientStream: stream}
	return x, nil
}

type FleetManager_HerdCommandStreamClient interface {
	Send(*CommandSteamRequest) error
	Recv() (*CommandSteamRespose, error)
	grpc.ClientStream
}

type fleetManagerHerdCommandStreamClient struct {
	grpc.ClientStream
}

func (x *fleetManagerHerdCommandStreamClient) Send(m *CommandSteamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fleetManagerHerdCommandStreamClient) Recv() (*CommandSteamRespose, error) {
	m := new(CommandSteamRespose)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fleetManagerClient) HerdServices(ctx context.Context, in *HerdServiceRequest, opts ...grpc.CallOption) (*HerdServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HerdServiceResponse)
	err := c.cc.Invoke(ctx, FleetManager_HerdServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetManagerClient) HerdRobotTelemetry(ctx context.Context, in *RobotTelemetryData, opts ...grpc.CallOption) (FleetManager_HerdRobotTelemetryClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetManager_ServiceDesc.Streams[1], FleetManager_HerdRobotTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &fleetManagerHerdRobotTelemetryClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FleetManager_HerdRobotTelemetryClient interface {
	Recv() (*RobotTelemetryResponse, error)
	grpc.ClientStream
}

type fleetManagerHerdRobotTelemetryClient struct {
	grpc.ClientStream
}

func (x *fleetManagerHerdRobotTelemetryClient) Recv() (*RobotTelemetryResponse, error) {
	m := new(RobotTelemetryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fleetManagerClient) HerdTelemetry(ctx context.Context, opts ...grpc.CallOption) (FleetManager_HerdTelemetryClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetManager_ServiceDesc.Streams[2], FleetManager_HerdTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &fleetManagerHerdTelemetryClient{ClientStream: stream}
	return x, nil
}

type FleetManager_HerdTelemetryClient interface {
	Send(*HerdTelemetryReqest) error
	CloseAndRecv() (*HerdTelemetryResponse, error)
	grpc.ClientStream
}

type fleetManagerHerdTelemetryClient struct {
	grpc.ClientStream
}

func (x *fleetManagerHerdTelemetryClient) Send(m *HerdTelemetryReqest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fleetManagerHerdTelemetryClient) CloseAndRecv() (*HerdTelemetryResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(HerdTelemetryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fleetManagerClient) HerdHealthCheck(ctx context.Context, opts ...grpc.CallOption) (FleetManager_HerdHealthCheckClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetManager_ServiceDesc.Streams[3], FleetManager_HerdHealthCheck_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &fleetManagerHerdHealthCheckClient{ClientStream: stream}
	return x, nil
}

type FleetManager_HerdHealthCheckClient interface {
	Send(*HealthCheckRequest) error
	Recv() (*HealthCheckResponse, error)
	grpc.ClientStream
}

type fleetManagerHerdHealthCheckClient struct {
	grpc.ClientStream
}

func (x *fleetManagerHerdHealthCheckClient) Send(m *HealthCheckRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fleetManagerHerdHealthCheckClient) Recv() (*HealthCheckResponse, error) {
	m := new(HealthCheckResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fleetManagerClient) DockerStatsTelemetry(ctx context.Context, in *DockerTelemetryRequest, opts ...grpc.CallOption) (FleetManager_DockerStatsTelemetryClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetManager_ServiceDesc.Streams[4], FleetManager_DockerStatsTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &fleetManagerDockerStatsTelemetryClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FleetManager_DockerStatsTelemetryClient interface {
	Recv() (*DockerTelemetryResponse, error)
	grpc.ClientStream
}

type fleetManagerDockerStatsTelemetryClient struct {
	grpc.ClientStream
}

func (x *fleetManagerDockerStatsTelemetryClient) Recv() (*DockerTelemetryResponse, error) {
	m := new(DockerTelemetryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FleetManagerServer is the server API for FleetManager service.
// All implementations must embed UnimplementedFleetManagerServer
// for forward compatibility
type FleetManagerServer interface {
	HerdCommandStream(FleetManager_HerdCommandStreamServer) error
	HerdServices(context.Context, *HerdServiceRequest) (*HerdServiceResponse, error)
	HerdRobotTelemetry(*RobotTelemetryData, FleetManager_HerdRobotTelemetryServer) error
	HerdTelemetry(FleetManager_HerdTelemetryServer) error
	HerdHealthCheck(FleetManager_HerdHealthCheckServer) error
	DockerStatsTelemetry(*DockerTelemetryRequest, FleetManager_DockerStatsTelemetryServer) error
	mustEmbedUnimplementedFleetManagerServer()
}

// UnimplementedFleetManagerServer must be embedded to have forward compatible implementations.
type UnimplementedFleetManagerServer struct {
}

func (UnimplementedFleetManagerServer) HerdCommandStream(FleetManager_HerdCommandStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method HerdCommandStream not implemented")
}
func (UnimplementedFleetManagerServer) HerdServices(context.Context, *HerdServiceRequest) (*HerdServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HerdServices not implemented")
}
func (UnimplementedFleetManagerServer) HerdRobotTelemetry(*RobotTelemetryData, FleetManager_HerdRobotTelemetryServer) error {
	return status.Errorf(codes.Unimplemented, "method HerdRobotTelemetry not implemented")
}
func (UnimplementedFleetManagerServer) HerdTelemetry(FleetManager_HerdTelemetryServer) error {
	return status.Errorf(codes.Unimplemented, "method HerdTelemetry not implemented")
}
func (UnimplementedFleetManagerServer) HerdHealthCheck(FleetManager_HerdHealthCheckServer) error {
	return status.Errorf(codes.Unimplemented, "method HerdHealthCheck not implemented")
}
func (UnimplementedFleetManagerServer) DockerStatsTelemetry(*DockerTelemetryRequest, FleetManager_DockerStatsTelemetryServer) error {
	return status.Errorf(codes.Unimplemented, "method DockerStatsTelemetry not implemented")
}
func (UnimplementedFleetManagerServer) mustEmbedUnimplementedFleetManagerServer() {}

// UnsafeFleetManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FleetManagerServer will
// result in compilation errors.
type UnsafeFleetManagerServer interface {
	mustEmbedUnimplementedFleetManagerServer()
}

func RegisterFleetManagerServer(s grpc.ServiceRegistrar, srv FleetManagerServer) {
	s.RegisterService(&FleetManager_ServiceDesc, srv)
}

func _FleetManager_HerdCommandStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FleetManagerServer).HerdCommandStream(&fleetManagerHerdCommandStreamServer{ServerStream: stream})
}

type FleetManager_HerdCommandStreamServer interface {
	Send(*CommandSteamRespose) error
	Recv() (*CommandSteamRequest, error)
	grpc.ServerStream
}

type fleetManagerHerdCommandStreamServer struct {
	grpc.ServerStream
}

func (x *fleetManagerHerdCommandStreamServer) Send(m *CommandSteamRespose) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fleetManagerHerdCommandStreamServer) Recv() (*CommandSteamRequest, error) {
	m := new(CommandSteamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _FleetManager_HerdServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HerdServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetManagerServer).HerdServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetManager_HerdServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetManagerServer).HerdServices(ctx, req.(*HerdServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetManager_HerdRobotTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RobotTelemetryData)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FleetManagerServer).HerdRobotTelemetry(m, &fleetManagerHerdRobotTelemetryServer{ServerStream: stream})
}

type FleetManager_HerdRobotTelemetryServer interface {
	Send(*RobotTelemetryResponse) error
	grpc.ServerStream
}

type fleetManagerHerdRobotTelemetryServer struct {
	grpc.ServerStream
}

func (x *fleetManagerHerdRobotTelemetryServer) Send(m *RobotTelemetryResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _FleetManager_HerdTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FleetManagerServer).HerdTelemetry(&fleetManagerHerdTelemetryServer{ServerStream: stream})
}

type FleetManager_HerdTelemetryServer interface {
	SendAndClose(*HerdTelemetryResponse) error
	Recv() (*HerdTelemetryReqest, error)
	grpc.ServerStream
}

type fleetManagerHerdTelemetryServer struct {
	grpc.ServerStream
}

func (x *fleetManagerHerdTelemetryServer) SendAndClose(m *HerdTelemetryResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fleetManagerHerdTelemetryServer) Recv() (*HerdTelemetryReqest, error) {
	m := new(HerdTelemetryReqest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _FleetManager_HerdHealthCheck_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FleetManagerServer).HerdHealthCheck(&fleetManagerHerdHealthCheckServer{ServerStream: stream})
}

type FleetManager_HerdHealthCheckServer interface {
	Send(*HealthCheckResponse) error
	Recv() (*HealthCheckRequest, error)
	grpc.ServerStream
}

type fleetManagerHerdHealthCheckServer struct {
	grpc.ServerStream
}

func (x *fleetManagerHerdHealthCheckServer) Send(m *HealthCheckResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fleetManagerHerdHealthCheckServer) Recv() (*HealthCheckRequest, error) {
	m := new(HealthCheckRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _FleetManager_DockerStatsTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DockerTelemetryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FleetManagerServer).DockerStatsTelemetry(m, &fleetManagerDockerStatsTelemetryServer{ServerStream: stream})
}

type FleetManager_DockerStatsTelemetryServer interface {
	Send(*DockerTelemetryResponse) error
	grpc.ServerStream
}

type fleetManagerDockerStatsTelemetryServer struct {
	grpc.ServerStream
}

func (x *fleetManagerDockerStatsTelemetryServer) Send(m *DockerTelemetryResponse) error {
	return x.ServerStream.SendMsg(m)
}

// FleetManager_ServiceDesc is the grpc.ServiceDesc for FleetManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FleetManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.fleet_manager.FleetManager",
	HandlerType: (*FleetManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HerdServices",
			Handler:    _FleetManager_HerdServices_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HerdCommandStream",
			Handler:       _FleetManager_HerdCommandStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "HerdRobotTelemetry",
			Handler:       _FleetManager_HerdRobotTelemetry_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "HerdTelemetry",
			Handler:       _FleetManager_HerdTelemetry_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "HerdHealthCheck",
			Handler:       _FleetManager_HerdHealthCheck_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "DockerStatsTelemetry",
			Handler:       _FleetManager_DockerStatsTelemetry_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protos/fleet_manager/v1/fleet_manager.proto",
}
