//
//##########################################################################################
//
//THIS PROTO IS DEPRECATED AND NOT USED IN LATEST VERSIONS
//LATEST VERSIONED AGENTS USE REST FOR COMMUNICATING BETWEEN WEB CLIENT /
//NODEJS AND SERVER.
//
//##########################################################################################

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: protos/node_sdk/v1/node_sdk.proto

package rcc

import (
	model "github.com/GOAT-Robotics/gtstudio-proto/protos/v1/model"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceCallReqest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *model.CommandRequest  `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceCallReqest) Reset() {
	*x = ServiceCallReqest{}
	mi := &file_protos_node_sdk_v1_node_sdk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceCallReqest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceCallReqest) ProtoMessage() {}

func (x *ServiceCallReqest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_node_sdk_v1_node_sdk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceCallReqest.ProtoReflect.Descriptor instead.
func (*ServiceCallReqest) Descriptor() ([]byte, []int) {
	return file_protos_node_sdk_v1_node_sdk_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceCallReqest) GetRequest() *model.CommandRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type ServiceCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *model.CommandResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceCallResponse) Reset() {
	*x = ServiceCallResponse{}
	mi := &file_protos_node_sdk_v1_node_sdk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceCallResponse) ProtoMessage() {}

func (x *ServiceCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_node_sdk_v1_node_sdk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceCallResponse.ProtoReflect.Descriptor instead.
func (*ServiceCallResponse) Descriptor() ([]byte, []int) {
	return file_protos_node_sdk_v1_node_sdk_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceCallResponse) GetResponse() *model.CommandResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type ActionCallReqest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *model.CommandRequest  `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionCallReqest) Reset() {
	*x = ActionCallReqest{}
	mi := &file_protos_node_sdk_v1_node_sdk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionCallReqest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionCallReqest) ProtoMessage() {}

func (x *ActionCallReqest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_node_sdk_v1_node_sdk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionCallReqest.ProtoReflect.Descriptor instead.
func (*ActionCallReqest) Descriptor() ([]byte, []int) {
	return file_protos_node_sdk_v1_node_sdk_proto_rawDescGZIP(), []int{2}
}

func (x *ActionCallReqest) GetRequest() *model.CommandRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type ActionCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *model.CommandResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionCallResponse) Reset() {
	*x = ActionCallResponse{}
	mi := &file_protos_node_sdk_v1_node_sdk_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionCallResponse) ProtoMessage() {}

func (x *ActionCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_node_sdk_v1_node_sdk_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionCallResponse.ProtoReflect.Descriptor instead.
func (*ActionCallResponse) Descriptor() ([]byte, []int) {
	return file_protos_node_sdk_v1_node_sdk_proto_rawDescGZIP(), []int{3}
}

func (x *ActionCallResponse) GetResponse() *model.CommandResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Topic         *model.StreamConfiguration `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_protos_node_sdk_v1_node_sdk_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_node_sdk_v1_node_sdk_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_protos_node_sdk_v1_node_sdk_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeRequest) GetTopic() *model.StreamConfiguration {
	if x != nil {
		return x.Topic
	}
	return nil
}

type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_protos_node_sdk_v1_node_sdk_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_node_sdk_v1_node_sdk_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_protos_node_sdk_v1_node_sdk_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *SubscribeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_protos_node_sdk_v1_node_sdk_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_node_sdk_v1_node_sdk_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_protos_node_sdk_v1_node_sdk_proto_rawDescGZIP(), []int{6}
}

func (x *UnsubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type UnsubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeResponse) Reset() {
	*x = UnsubscribeResponse{}
	mi := &file_protos_node_sdk_v1_node_sdk_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeResponse) ProtoMessage() {}

func (x *UnsubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_node_sdk_v1_node_sdk_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeResponse.ProtoReflect.Descriptor instead.
func (*UnsubscribeResponse) Descriptor() ([]byte, []int) {
	return file_protos_node_sdk_v1_node_sdk_proto_rawDescGZIP(), []int{7}
}

func (x *UnsubscribeResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *UnsubscribeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetTopicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicsRequest) Reset() {
	*x = GetTopicsRequest{}
	mi := &file_protos_node_sdk_v1_node_sdk_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicsRequest) ProtoMessage() {}

func (x *GetTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_node_sdk_v1_node_sdk_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicsRequest.ProtoReflect.Descriptor instead.
func (*GetTopicsRequest) Descriptor() ([]byte, []int) {
	return file_protos_node_sdk_v1_node_sdk_proto_rawDescGZIP(), []int{8}
}

type GetTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Data          []*model.ROSTopic      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicsResponse) Reset() {
	*x = GetTopicsResponse{}
	mi := &file_protos_node_sdk_v1_node_sdk_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicsResponse) ProtoMessage() {}

func (x *GetTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_node_sdk_v1_node_sdk_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicsResponse.ProtoReflect.Descriptor instead.
func (*GetTopicsResponse) Descriptor() ([]byte, []int) {
	return file_protos_node_sdk_v1_node_sdk_proto_rawDescGZIP(), []int{9}
}

func (x *GetTopicsResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *GetTopicsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetTopicsResponse) GetData() []*model.ROSTopic {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetSubscrbedTopicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscrbedTopicsRequest) Reset() {
	*x = GetSubscrbedTopicsRequest{}
	mi := &file_protos_node_sdk_v1_node_sdk_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscrbedTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscrbedTopicsRequest) ProtoMessage() {}

func (x *GetSubscrbedTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_node_sdk_v1_node_sdk_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscrbedTopicsRequest.ProtoReflect.Descriptor instead.
func (*GetSubscrbedTopicsRequest) Descriptor() ([]byte, []int) {
	return file_protos_node_sdk_v1_node_sdk_proto_rawDescGZIP(), []int{10}
}

type GetSubscrbedTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Data          []*model.ROSTopic      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscrbedTopicsResponse) Reset() {
	*x = GetSubscrbedTopicsResponse{}
	mi := &file_protos_node_sdk_v1_node_sdk_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscrbedTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscrbedTopicsResponse) ProtoMessage() {}

func (x *GetSubscrbedTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_node_sdk_v1_node_sdk_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscrbedTopicsResponse.ProtoReflect.Descriptor instead.
func (*GetSubscrbedTopicsResponse) Descriptor() ([]byte, []int) {
	return file_protos_node_sdk_v1_node_sdk_proto_rawDescGZIP(), []int{11}
}

func (x *GetSubscrbedTopicsResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *GetSubscrbedTopicsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetSubscrbedTopicsResponse) GetData() []*model.ROSTopic {
	if x != nil {
		return x.Data
	}
	return nil
}

type PublishRequest struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	Id               string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ControlDatapoint *model.ControlDatapoint `protobuf:"bytes,2,opt,name=control_datapoint,json=controlDatapoint,proto3" json:"control_datapoint,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_protos_node_sdk_v1_node_sdk_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_node_sdk_v1_node_sdk_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_protos_node_sdk_v1_node_sdk_proto_rawDescGZIP(), []int{12}
}

func (x *PublishRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublishRequest) GetControlDatapoint() *model.ControlDatapoint {
	if x != nil {
		return x.ControlDatapoint
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_protos_node_sdk_v1_node_sdk_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_node_sdk_v1_node_sdk_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_protos_node_sdk_v1_node_sdk_proto_rawDescGZIP(), []int{13}
}

func (x *PublishResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *PublishResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_protos_node_sdk_v1_node_sdk_proto protoreflect.FileDescriptor

const file_protos_node_sdk_v1_node_sdk_proto_rawDesc = "" +
	"\n" +
	"!protos/node_sdk/v1/node_sdk.proto\x12\x06v1.rcc\x1a\x1eprotos/model/v1/commands.proto\x1a\x1cprotos/model/v1/config.proto\x1a\x19protos/model/v1/ros.proto\x1a\x1fprotos/model/v1/datapoint.proto\"G\n" +
	"\x11ServiceCallReqest\x122\n" +
	"\arequest\x18\x01 \x01(\v2\x18.v1.model.CommandRequestR\arequest\"L\n" +
	"\x13ServiceCallResponse\x125\n" +
	"\bresponse\x18\x01 \x01(\v2\x19.v1.model.CommandResponseR\bresponse\"F\n" +
	"\x10ActionCallReqest\x122\n" +
	"\arequest\x18\x01 \x01(\v2\x18.v1.model.CommandRequestR\arequest\"K\n" +
	"\x12ActionCallResponse\x125\n" +
	"\bresponse\x18\x01 \x01(\v2\x19.v1.model.CommandResponseR\bresponse\"G\n" +
	"\x10SubscribeRequest\x123\n" +
	"\x05topic\x18\x01 \x01(\v2\x1d.v1.model.StreamConfigurationR\x05topic\"A\n" +
	"\x11SubscribeResponse\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"*\n" +
	"\x12UnsubscribeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"C\n" +
	"\x13UnsubscribeResponse\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x12\n" +
	"\x10GetTopicsRequest\"i\n" +
	"\x11GetTopicsResponse\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12&\n" +
	"\x04data\x18\x01 \x03(\v2\x12.v1.model.ROSTopicR\x04data\"\x1b\n" +
	"\x19GetSubscrbedTopicsRequest\"r\n" +
	"\x1aGetSubscrbedTopicsResponse\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12&\n" +
	"\x04data\x18\x01 \x03(\v2\x12.v1.model.ROSTopicR\x04data\"i\n" +
	"\x0ePublishRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12G\n" +
	"\x11control_datapoint\x18\x02 \x01(\v2\x1a.v1.model.ControlDatapointR\x10controlDatapoint\"?\n" +
	"\x0fPublishResponse\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\x8a\x04\n" +
	"\aNodeSdk\x12G\n" +
	"\vServiceCall\x12\x19.v1.rcc.ServiceCallReqest\x1a\x1b.v1.rcc.ServiceCallResponse\"\x00\x12F\n" +
	"\n" +
	"ActionCall\x12\x18.v1.rcc.ActionCallReqest\x1a\x1a.v1.rcc.ActionCallResponse\"\x000\x01\x12B\n" +
	"\tSubscribe\x12\x18.v1.rcc.SubscribeRequest\x1a\x19.v1.rcc.SubscribeResponse\"\x00\x12H\n" +
	"\vUnsubscribe\x12\x1a.v1.rcc.UnsubscribeRequest\x1a\x1b.v1.rcc.UnsubscribeResponse\"\x00\x12B\n" +
	"\tGetTopics\x12\x18.v1.rcc.GetTopicsRequest\x1a\x19.v1.rcc.GetTopicsResponse\"\x00\x12^\n" +
	"\x13GetSubscribedTopics\x12!.v1.rcc.GetSubscrbedTopicsRequest\x1a\".v1.rcc.GetSubscrbedTopicsResponse\"\x00\x12<\n" +
	"\aPublish\x12\x16.v1.rcc.PublishRequest\x1a\x17.v1.rcc.PublishResponse\"\x00B7Z5github.com/GOAT-Robotics/gtstudio-proto/protos/v1/rccb\x06proto3"

var (
	file_protos_node_sdk_v1_node_sdk_proto_rawDescOnce sync.Once
	file_protos_node_sdk_v1_node_sdk_proto_rawDescData []byte
)

func file_protos_node_sdk_v1_node_sdk_proto_rawDescGZIP() []byte {
	file_protos_node_sdk_v1_node_sdk_proto_rawDescOnce.Do(func() {
		file_protos_node_sdk_v1_node_sdk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_node_sdk_v1_node_sdk_proto_rawDesc), len(file_protos_node_sdk_v1_node_sdk_proto_rawDesc)))
	})
	return file_protos_node_sdk_v1_node_sdk_proto_rawDescData
}

var file_protos_node_sdk_v1_node_sdk_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_protos_node_sdk_v1_node_sdk_proto_goTypes = []any{
	(*ServiceCallReqest)(nil),          // 0: v1.rcc.ServiceCallReqest
	(*ServiceCallResponse)(nil),        // 1: v1.rcc.ServiceCallResponse
	(*ActionCallReqest)(nil),           // 2: v1.rcc.ActionCallReqest
	(*ActionCallResponse)(nil),         // 3: v1.rcc.ActionCallResponse
	(*SubscribeRequest)(nil),           // 4: v1.rcc.SubscribeRequest
	(*SubscribeResponse)(nil),          // 5: v1.rcc.SubscribeResponse
	(*UnsubscribeRequest)(nil),         // 6: v1.rcc.UnsubscribeRequest
	(*UnsubscribeResponse)(nil),        // 7: v1.rcc.UnsubscribeResponse
	(*GetTopicsRequest)(nil),           // 8: v1.rcc.GetTopicsRequest
	(*GetTopicsResponse)(nil),          // 9: v1.rcc.GetTopicsResponse
	(*GetSubscrbedTopicsRequest)(nil),  // 10: v1.rcc.GetSubscrbedTopicsRequest
	(*GetSubscrbedTopicsResponse)(nil), // 11: v1.rcc.GetSubscrbedTopicsResponse
	(*PublishRequest)(nil),             // 12: v1.rcc.PublishRequest
	(*PublishResponse)(nil),            // 13: v1.rcc.PublishResponse
	(*model.CommandRequest)(nil),       // 14: v1.model.CommandRequest
	(*model.CommandResponse)(nil),      // 15: v1.model.CommandResponse
	(*model.StreamConfiguration)(nil),  // 16: v1.model.StreamConfiguration
	(*model.ROSTopic)(nil),             // 17: v1.model.ROSTopic
	(*model.ControlDatapoint)(nil),     // 18: v1.model.ControlDatapoint
}
var file_protos_node_sdk_v1_node_sdk_proto_depIdxs = []int32{
	14, // 0: v1.rcc.ServiceCallReqest.request:type_name -> v1.model.CommandRequest
	15, // 1: v1.rcc.ServiceCallResponse.response:type_name -> v1.model.CommandResponse
	14, // 2: v1.rcc.ActionCallReqest.request:type_name -> v1.model.CommandRequest
	15, // 3: v1.rcc.ActionCallResponse.response:type_name -> v1.model.CommandResponse
	16, // 4: v1.rcc.SubscribeRequest.topic:type_name -> v1.model.StreamConfiguration
	17, // 5: v1.rcc.GetTopicsResponse.data:type_name -> v1.model.ROSTopic
	17, // 6: v1.rcc.GetSubscrbedTopicsResponse.data:type_name -> v1.model.ROSTopic
	18, // 7: v1.rcc.PublishRequest.control_datapoint:type_name -> v1.model.ControlDatapoint
	0,  // 8: v1.rcc.NodeSdk.ServiceCall:input_type -> v1.rcc.ServiceCallReqest
	2,  // 9: v1.rcc.NodeSdk.ActionCall:input_type -> v1.rcc.ActionCallReqest
	4,  // 10: v1.rcc.NodeSdk.Subscribe:input_type -> v1.rcc.SubscribeRequest
	6,  // 11: v1.rcc.NodeSdk.Unsubscribe:input_type -> v1.rcc.UnsubscribeRequest
	8,  // 12: v1.rcc.NodeSdk.GetTopics:input_type -> v1.rcc.GetTopicsRequest
	10, // 13: v1.rcc.NodeSdk.GetSubscribedTopics:input_type -> v1.rcc.GetSubscrbedTopicsRequest
	12, // 14: v1.rcc.NodeSdk.Publish:input_type -> v1.rcc.PublishRequest
	1,  // 15: v1.rcc.NodeSdk.ServiceCall:output_type -> v1.rcc.ServiceCallResponse
	3,  // 16: v1.rcc.NodeSdk.ActionCall:output_type -> v1.rcc.ActionCallResponse
	5,  // 17: v1.rcc.NodeSdk.Subscribe:output_type -> v1.rcc.SubscribeResponse
	7,  // 18: v1.rcc.NodeSdk.Unsubscribe:output_type -> v1.rcc.UnsubscribeResponse
	9,  // 19: v1.rcc.NodeSdk.GetTopics:output_type -> v1.rcc.GetTopicsResponse
	11, // 20: v1.rcc.NodeSdk.GetSubscribedTopics:output_type -> v1.rcc.GetSubscrbedTopicsResponse
	13, // 21: v1.rcc.NodeSdk.Publish:output_type -> v1.rcc.PublishResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_protos_node_sdk_v1_node_sdk_proto_init() }
func file_protos_node_sdk_v1_node_sdk_proto_init() {
	if File_protos_node_sdk_v1_node_sdk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_node_sdk_v1_node_sdk_proto_rawDesc), len(file_protos_node_sdk_v1_node_sdk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_node_sdk_v1_node_sdk_proto_goTypes,
		DependencyIndexes: file_protos_node_sdk_v1_node_sdk_proto_depIdxs,
		MessageInfos:      file_protos_node_sdk_v1_node_sdk_proto_msgTypes,
	}.Build()
	File_protos_node_sdk_v1_node_sdk_proto = out.File
	file_protos_node_sdk_v1_node_sdk_proto_goTypes = nil
	file_protos_node_sdk_v1_node_sdk_proto_depIdxs = nil
}
